apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: schoolmgt
build:
  artifacts:
  - image: school-management
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  local: 
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/k8s-pod.yaml
portForward:
- resourceType: pod
  resourceName: school-management-svc
  namespace: default
  port: 9000
  localPort: 9000 # *Optional*